prompt_template: "Provide a concise and comprehensive Response to the Instruction considering the given Context and include your reasoning. \n### Context:\n{context}\n### Instruction:\n{query}\n### Response:"
inference_model:
  model_import_path: "ctransformers.AutoModelForCausalLM"
  model_params:
    model_path: "TheBloke/Starcoderplus-Guanaco-GPT4-15B-V1.0-GGML"
    model_type: "starcoder"
    local_files_only: false
    lib: "avx2"
    threads: 30
    max_new_tokens: 2048
